# Generated by Django 5.2 on 2025-04-22 17:09

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0003_fotografia_publicada"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="data_fotografia",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 4, 22, 14, 9, 5, 467004)
            ),
        ),
    ]
